blueprint:
  name: Turn On White Light with Motion and Low Illuminance
  description: >
    Turns on a white light when motion is detected and the illuminance sensor reports "dim" 
    during a specific time range.
  domain: automation
  input:
    presence_sensor:
      name: Motion Sensor
      description: Select the motion sensor.
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy

    illuminance_sensor:
      name: Illuminance Sensor
      description: Select the ambient illuminance sensor.
      selector:
        entity:
          domain: sensor

    light_entity:
      name: White Light
      description: Select the light to be turned on.
      selector:
        entity:
          domain: light

    delay_seconds:
      name: Delay Before Turning On (seconds)
      description: Wait time before turning on the light.
      default: 1
      selector:
        number:
          min: 0
          max: 5
          unit_of_measurement: "s"
          mode: slider

    start_time:
      name: Start Time
      description: Choose the time when the automation is active.
      default: "17:00:00"
      selector:
        time: {}

    end_time:
      name: End Time
      description: Choose the time when the automation stops running.
      default: "07:00:00"
      selector:
        time: {}

mode: restart

trigger:
  - platform: state
    entity_id: !input presence_sensor
    from: "off"
    to: "on"

  - platform: state
    entity_id: !input illuminance_sensor
    to: "dim"

condition:
  - condition: time
    after: !input start_time
    before: !input end_time

action:
  - delay:
      seconds: !input delay_seconds
  - service: light.turn_on
    target:
      entity_id: !input light_entity
